### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#26]
**3 Questions:**
1. Am I correct to use "float"?

2. I'm not clear why this last line of code isn't working (I get an error):

print(f"The tip amount is ${:.2f}".format(tip_calculation))

3. To convert a number to a decimal is "{:.2f}".format" something I just need to memorize?

Here's the code:
#step1: ask user for bill amount
bill_amount = float(input("What was the bill amount? "))

#step2: ask user for tip rate
tip_rate = float(input("What is your tip rate? "))

#step3: calculate tip from an integer to a decimal
tip_calculation = tip_rate/100 * bill_amount

#print statement with tip amount
print(f"The tip amount is ${:.2f}".format(tip_calculation))

**Comment by paulghaddad** [comment]
@amymhaddad You are exactly correct in using `float` here. The issue with the code is that `f""` automatically interpolates variables inside curly braces. But you're using the `format` method, and thus you only need to use a string:

```
print("The tip amount is ${:.2f}".format(tip_calculation))
```
