### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#27]
I'm working on indexing and unclear about this problem: 

secret = "mai p455w_zero_rD"
secret [-1:-8]

I have to evaluate the expression. The answer is: "empty string b/c the start index is further in the string than the stop index." However, isn't the start index "D" and the stop index "_"? So the answer should be "Dr_orez" (the step is "1" since it's not defined).

**Comment by paulghaddad** [comment]
@amymhaddad You have to think of it as always slicing from left to right, but that the negative indexes are simply an alternate way of expressing the index. So this would be:

```
secret[-8:-1]
```

It slices from the -8 position to, but NOT including, the last character. If you want to last character too, then you just leave off the -1:

```
secret[-8:]
```

**Comment by paulghaddad** [comment]
@amymhaddad Here is a good reference for this:

https://www.digitalocean.com/community/tutorials/how-to-index-and-slice-strings-in-python-3

**Comment by paulghaddad** [comment]
@amymhaddad This whole series is actually good: https://www.digitalocean.com/community/tutorial_series/how-to-code-in-python-3
