### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#32]
Constant must be a single value, such as a string or number, that never changes. area = L * W is a statement that changes with different values of L and W.

**Comment by paulghaddad** [comment]
Correct

**Comment by paulghaddad** [comment]
Correct. A constant can only represent a _single_ value that shouldn't change, such as Pi. L x W contains two things, both of which could change, thus they are normal variables, since they _vary_.
