### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#47]
Instructions: Ask the user for two numbers. Print their sum. If the sum is less than zero, also print "Wow, negative sum!"

number_1 = int(input("Enter a number: "))
number_2 = int(input("Enter a second number: "))

sum = number_1 + number_2
print(sum)

If number_1+number_2 < 0:
    print("Wow, negative sum!")

**Comment by paulghaddad** [comment]
You need to indent the code that runs after the `if` statement:

```
If number_1+number_2 < 0:
  print("Wow, negative sum!")
```
