### ISSUE TITLE
Conditionals - 2

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#49]
Two examples I have questions about:

Example 1:
word = input("Enter a word: ")

if " " in word:
    print("User didn't follow directions.")

--->The code above works, but why can't the code below work as well (using the ==):

word = input("Enter a word: ")

if word == " ":
    print("User didn't follow directions.")

Example 2:

This code works and I understand why:

user_info = "words"
if type(user_info) == str:
    print("I'm a words person")

----->But why can't I type something like this:

user_info = "words"
if str in user.info:
    print("I'm a words person")

**Comment by paulghaddad** [comment]
@amymhaddad Let's do this in person.
