### ISSUE TITLE
Math Equations

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#50]
I'm trying to print math equations and have Python solve them -- without any commas or parentheses.

Example:
addition = ("4 + 4 =", 4+4)

Is there a way to do that without using variables for each number?

**Comment by paulghaddad** [comment]
This should work! Anything inside the curly braces is evaluated as normal python code, whether it's this or a simple variable name.

`print(f'4 + 4 = {4+4}')
