### ISSUE TITLE
Conditional ex question

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#72]
Instruction: 
You're given the following two statements:
"x is an odd number" and "x + 1 is an even number" 
Write a conditional statement and outcome.

if x % 2 != 0:
   print("x is an odd number")
   print("x + 1 is an even number")

**Comment by paulghaddad** [comment]
Perfect! One tweak is how to handle is x turns out to be odd, so you can just add an `else`:

```
if x % 2 != 0:
  print("x is an odd number")
  print("x + 1 is an even number")
else:
  print("x is an even number")
  print("x + 1 is an odd number")
```

I'd suggest testing this with an actual odd, and then even number, and making sure both conditional paths work.

**Comment by amymhaddad** [comment]
@paulghaddad perfect - thanks!
