### ISSUE TITLE
.format

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#75]
I'm not clear about how to reduce the amount of code when using .format() twice in the same line of code. I get an error when I remove the first instance of ".format(....)":

# Step 1: set constant
WI_TAX = 5.5

# Step 2: get input from user
order_amount = int(input("Enter the order amount:$"))
state = input("Enter your state (use state abbreviations): ")
normalized_state = state.lower()

# Step 3: write conditional
if normalized_state == "wi":
    tax = (WI_TAX / 100) * order_amount
    print("You're going to pay ${:.2f}".format(tax) + " in tax.")
    subtotal = order_amount + tax
--> print("Your order total is ${:.2f}, but with tax your subtotal comes to ${:.2f}.".format(subtotal)
#The above line is the one in question and the one I get an error. How does Python know what to print #if I remove the first .format()?
else:
    print(f"Your subtotal is ${order_amount}.")

**Comment by paulghaddad** [comment]
If you have two placeholders, `{}`, then you have to pass in two parameters to `.format`:

```
print("Your order total is ${:.2f}, but with tax your subtotal comes to ${:.2f}.".format(order_amount, subtotal)
```
